services:
  - type: web
    name: devportfolio-pro-server
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production